version: '3.9'

services:
  db:
    image: postgres:14.1-alpine
    ports: 
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT}
    depends_on:
      - db
    command:
      - '/bin/sh'
      - '-c'
      - '/bin/sleep 5 && npm start'
volumes:
  db:
    driver: local